### ISSUE TITLE
npm build fails, but local use with npm start is OK

### ISSUE THREAD

**Issue by buckybots** [react-spring/zustand#88]
I have been using npm start, and there have been no issues.  I tried npm build and got the following:

$ npm run build

> iotvid-client@0.1.0 build C:\d-client
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/zustand/index.js:5

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iotvid-client@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the d-client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

--------------------------------------------------------------------------------------------------------
here is the complete log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.3.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iotvid-client@0.1.0~prebuild: iotvid-client@0.1.0
6 info lifecycle iotvid-client@0.1.0~build: iotvid-client@0.1.0
7 verbose lifecycle iotvid-client@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle iotvid-client@0.1.0~build: PATH: C:\Users\e\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\d-client\node_modules\.bin;C:\Program Files  ........removed..........
9 verbose lifecycle iotvid-client@0.1.0~build: CWD: C:\d-client
10 silly lifecycle iotvid-client@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle iotvid-client@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle iotvid-client@0.1.0~build: Failed to exec build script
13 verbose stack Error: d-client@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\e\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\e\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid iotvid-client@0.1.0
15 verbose cwd C:\d-client
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\e\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error d-client@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the d-client@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

------------------------------------------------------------------------------------------------------

Any idea why this is not building.  I do think the problem is with zustrand, as run build was working before adding this.

**Comment by buckybots** [comment]
found solution.  needed to update my npm react-scripts package to greater than 2.x.x.  This fixed the problem
